image: node:12.1.0

cache:
  paths:
    - postcode-web/node_modules/
    - postcode-api/node_modules/

stages:
  - test
  - build-web

test-web:
  stage: test
  before_script:
    - cd postcode-web/
    - npm install
  script:
    - npm test

test-api:
  stage: test
  before_script:
    - cd postcode-api/
    - npm install
  script:
    - npm test

lint-api:
  stage: test
  before_script:
    - cd postcode-api/
    - npm install
  script:
    - ./node_modules/.bin/eslint index.js

build-web:
  stage: build-web
  before_script:
    - cd postcode-web/
  script:
    - npm build