image: node:8.9.4

stages:
  - npm
  - test-api

npm:
  stage: npm
  script:
    - npm install
  cache:
    paths:
      - postcode-api/node_modules/
      - postcode-web/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - postcode-api/node_modules/
      - postcode-web/node_modules/

test-api:
  stage: test-api
  dependencies:
    - npm
  before_script:
    - cd postcode-api/
  script:
    - npm test
