image: node:8.9.4

stages:
  - setup-api
  - test-api

setup-api:
  stage: setup-api
  script:
    - cd postcode-api/
    - npm install

test-api:
  stage: test-api
  dependencies:
    - setup-api
  before_script:
    - cd postcode-api/
  script:
    - npm test