image: node:8.9.4

cache:
  paths:
  - postcode-web/node_modules/
  - postcode-api/node_modules/

stages:
  - test-web
  - test-api

test-web:
  stage: test-web
  before_script:
    - cd postcode-web/
    - npm install
  script:
    - npm test

test-api:
  stage: test-api
  before_script:
    - cd postcode-api/
    - npm install
  script:
    - npm test