version: "3"
services:
  db:
    container_name: postcode_db
    image: postcode-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: postcodeapi
      MYSQL_PASSWORD: root
    ports: [42333:3306]
  frontend:
    container_name: postcode_web
    build:
      context: ./postcode-web
      dockerfile: Dockerfile
    image: postcode-web
    ports:
      - "80:80"
    volumes:
      - ./postcode-web:/usr/src/app
  backend:
    container_name: postcode_api
    build:
      context: ./postcode-api
      dockerfile: Dockerfile
    image: postcode-api
    ports:
      - "4000:4000"
    volumes:
      - ./postcode-api:/usr/src/app
