version: "3"
services:
  postcode_db:
    container_name: postcode_db
    image: mysql:5.7.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: postcodeapi
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
  postcode_web:
    container_name: postcode_web
    build:
      context: ./postcode-web
      dockerfile: Dockerfile
    image: postcode-web
    ports:
      - "80:80"
    volumes:
      - ./postcode-web:/usr/src/app
    depends_on: 
      - postcode_api
    networks:
      - app-network
  postcode_api:
    container_name: postcode_api
    build:
      context: ./postcode-api
      dockerfile: Dockerfile
    image: postcode-api
    ports:
      - "4000:4000"
    volumes:
      - ./postcode-api:/usr/src/app
    depends_on: 
      - postcode_db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes: 
  mysql-data:
